### ISSUE TITLE
Mismatched column names prevents nhd_plus_query from binding flowlines from two separate HUCs

### ISSUE THREAD

**Issue by matthewross07** [jsta/nhdR#57]
This is an excellent package and really helpful and I'm grateful for your work. I'm hoping to incorporate this package into my workflows, but I came across a small bug today. Basically if you have two different hucs covered by a polygon or coordinates, and the objects in those hucs don't have the same column names, then the flowline (or waterbody) data won't bind. So you get this error message: 

`Error in rbind.data.frame(...) : 
  numbers of columns of arguments do not match`

I looked in your code and couldn't quite figure out where you are binding the nhd data, but happy to help (maybe you can drop some of the less useful NHD PLUS column names and guarantee equal column widths for all data). 

Thanks again!

**Comment by matthewross07** [comment]
And something more useful. The code below reproduces the error on my machine R 3.5.3: 

`box = st_bbox(c(xmin=-105.93003,xmax=-104.91784,
                ymin=40.41176,ymax=41.21014),crs=st_crs(4326)) %>%
  st_as_sfc()

poudre_flow <- nhd_plus_query(poly=box,
                               dsn=c('NHDFlowLine'))`

**Comment by jsta** [comment]
Thanks for the report! An even simpler command to throw this error is:

`nhd_plus_load(vpu = c("10L", "14"), dsn = "NHDFlowLine")`

**Comment by jsta** [comment]
The binding happens at: https://github.com/jsta/nhdR/blob/master/R/load.R#L247 

This issue is related to https://github.com/r-spatial/sf/issues/49

**Comment by jsta** [comment]
@matthewross07 I think the latest commits fix the issue. Let me know if they don't.
