### ISSUE TITLE
upcoming sf breaks nhdR on CRAN

### ISSUE THREAD

**Issue by edzer** [jsta/nhdR#62]
See
* https://www.r-spatial.org/r/2020/03/17/wkt.html
* https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt

Your tests don't pass with the new crs logic in upcoming sf. You could for instance use
```
expect_true(st_crs(toUTM(big_combined)) == st_crs(toUTM(sunapee$sp$NHDWaterbody)))
```
as an alternative: these crs are (now) semantically equal, but different in their represenation. Pls modify and submit to CRAN.

**Comment by jsta** [comment]
Changed to use the suggested logic. FWIW I updated my `sf` to the 0.9 but didn't raise any errors with the old test logic...
