### ISSUE TITLE
nhd_plus_load examples do not run

### ISSUE THREAD

**Issue by vlahm** [jsta/nhdR#66]
``` r
library(nhdR)
#> Loading required package: maps
dt <- nhd_plus_load(4, "NHDSnapshot", "NHDWaterbody")
#> Error in FUN(X[[i]], ...): layer 'NHDWaterbody' not found in component 'NHDSnapshot'
dt <- nhd_plus_load(1, "NHDPlusAttributes", "PlusFlow")
#> Error in FUN(X[[i]], ...): layer 'PlusFlow' not found in component 'NHDPlusAttributes'
```

<sup>Created on 2021-02-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jsta** [comment]
Are you using the latest version (`0.5.4`)? If yes, has the function worked for you on older versions?

**Comment by vlahm** [comment]
I am using 0.5.4. I also tried 0.5.3 and 0.5.2 just now, but got the same error across all three versions. This function worked for me about 6 months ago, though I don't know which version I was using at the time (surely one of those three).

**Comment by vlahm** [comment]
I'm on Ubuntu 20.04.

**Comment by jsta** [comment]
Strange, it works for me out of the box with a fresh data directory. Can you try these commands before rerunning the examples:
```
nhd_plus_get(4, force_dl = TRUE)
nhd_plus_get(4, force_unzip = TRUE)
```

The data store checks for the presence of the download archive but `nhd_plus_load` tries to read from the unzipped files. It's possible you're stuck in a situation where the download archive exists but there was a problem with the unzipping.

**Comment by vlahm** [comment]
Okay, that resolves the issue for

`dt <- nhdR::nhd_plus_load(4, "NHDSnapshot", "NHDWaterbody")`

but not for

`dt <- nhdR::nhd_plus_load(4, "NHDPlusAttributes", "PlusFlow")`

Here's what I've got:

```
> nhdR::nhd_plus_get(4, force_dl = TRUE)
Loading required namespace: digest
Re-downloading https://s3.amazonaws.com/edap-nhdplus/NHDPlusV21/Data/NHDPlusGL/NHDPlusV21_GL_04_NHDSnapshot_08.7z
  |=======================================================================================================================================================| 100%
A local copy of https://s3.amazonaws.com/edap-nhdplus/NHDPlusV21/Data/NHDPlusGL/NHDPlusV21_GL_04_NHDSnapshot_08.7z already exists on disk
> nhdR::nhd_plus_get(4, force_unzip = TRUE)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,48 CPUs AMD Ryzen Threadripper 3960X 24-Core Processor  (830F10),ASM,AES-NI)

Scanning the drive for archives:
1 file, 68772238 bytes (66 MiB)

Extracting archive: /home/mike/.local/share/nhdR/NHDPlus/NHDPlusV21_GL_04_NHDSnapshot_08.7z
--
Path = /home/mike/.local/share/nhdR/NHDPlus/NHDPlusV21_GL_04_NHDSnapshot_08.7z
Type = 7z
Physical Size = 68772238
Headers Size = 821
Method = LZMA:24
Solid = +
Blocks = 1

Everything is Ok

Folders: 4
Files: 37
Size:       268965416
Compressed: 68772238

> dt <- nhdR::nhd_plus_load(4, "NHDSnapshot", "NHDWaterbody")
Reading layer `NHDWaterbody' from data source `/home/mike/.local/share/nhdR/NHDPlus/GL_04_NHDSnapshot/NHDWaterbody.shp' using driver `ESRI Shapefile'
Simple feature collection with 31830 features and 12 fields
geometry type:  POLYGON
dimension:      XYZ
bbox:           xmin: -93.24332 ymin: 40.43575 xmax: -73.61814 ymax: 48.11344
z_range:        zmin: 0 zmax: 0
geographic CRS: NAD83

> dt <- nhdR::nhd_plus_load(4, "NHDPlusAttributes", "PlusFlow")
Error in FUN(X[[i]], ...) : 
  layer 'PlusFlow' not found in component 'NHDPlusAttributes'
```

**Comment by jsta** [comment]
You may need to run a similar `nhd_plus_get` + `force_unzip` command with the NHDPlusAttributes component:

```
nhd_plus_get(vpu = 4, component = "NHDPlusAttributes", force_unzip = TRUE)
```

**Comment by vlahm** [comment]
Ah, I see. Well, this solves my problem. I suppose if it's rare enough, there's no need to address it further and we can close this issue. But a quick improvement might be to check for a zip when the "layer not found" error is raised and unzip it automatically. Or, even just change the error message to indicate that the user should try running nhd_plus_get with force_unzip = TRUE. Thanks for your help.
