### ISSUE TITLE
Possible to query UPSTREAM flow length from NHDPlus?

### ISSUE THREAD

**Issue by alherca73** [jsta/nhdR#73]
Hello. I just came across your package and was wondering if it is possible to extract flow length at an outlet point from NHDPlus dataset? Something similar to ArcMap's Upstream flow length that is extracted from a Flow Direction grid?

Thanks,

**Comment by jsta** [comment]
Possibly, I am not very familiar with ArcMap. What do you mean by an "outlet point"? Is it a flowline node (on the stream network) or an XY point (off the stream network)?

**Comment by alherca73** [comment]
Hello. I should probably rephrase the question. Is it possible to query a flowline and extract its flow length? The outlet point or pour point would be the point of the surface where water flows out of a watershed. If I can query a flowline, and within NHDPlus the flow length is one of the attributes of that flow line, then I could extract this value for the pour point. Does that make sense?

**Comment by jsta** [comment]
Yep, so if we follow the steps in the [network vignette](https://jsta.github.io/nhdR/articles/network.html), running `sum(sf::st_length(mendota_network))` will return the upstream flow length.

**Comment by alherca73** [comment]
Thanks. I've been trying to run the code on that vignette but Rstudio keeps crashing... not sure what is going on.

**Comment by jsta** [comment]
Closing for now. Happy to reopen.
