### ISSUE TITLE
nhd_plus_query throws HTTP error 403 error

### ISSUE THREAD

**Issue by rstessier** [jsta/nhdR#88]
Hello! I am trying to create a map of Pacific Northwest rivers. This snippet of code was working earlier this week:

_hydro_qry <- nhd_plus_query(lon=-118,lat=46,
                            dsn="NHDFlowline")_

... but now it gives the following error: _Error in open.connection(x, "rb") : HTTP error 403._

I also sometimes receive the following warning, but I am not sure if they two issues are connected:
_Warning message:
In match(x, table, nomatch = 0L) :
  closing unused connection 3 (https://s3.amazonaws.com/edap-nhdplus?delimiter=/&prefix=NHDPlusV21/Data/NHDPlusSR/)_

I have tried the command on different machines and versions of RStudio. I have also tried updating all related packages. Please let me know what I can do to get this function working again. Thank you so much!
-Rachel

Edit: If I follow the amzonaws.com link, I see an information free with a host ID, request ID, and it says that access was denied.

**Comment by jsta** [comment]
I believe this has been fixed in the latest merge-commit #87. Try installing the latest source version from Github:
`devtools::install_github("jsta/nhdR")`

**Comment by rstessier** [comment]
That worked! Thank you so much - not only for you guidance but for how quickly you responded.
