### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [jsta/nhdR#91]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

`nhdR` imports 'rgdal' (and suggests 'rgeos') using `rgdal::ogrInfo`, `rgdal::ogrListLayers`, in NAMESPACE, `rgdal::ogrInfo` lines 13, 41 in R/info.R, `rgdal::ogrListLayers` line 41 in R/list.R. `rgdal::ogrListLayers` can be replaced by `sf::st_layers`, there is no replacement for `rgdal::ogrInfo` other than reading the whole object with `sf::st_read`.  Note that `@return An ogrinfo object from the sf package` is wrong, the object is only defined in `rgdal`. The suggested `rgeos` appears to be redundant. Please fix best by June, latest October 2023.

**Comment by jsta** [comment]
resolved with version 0.6.0 now on CRAN
